MODULE ERRORESTIMATE

	USE BASIS
	USE LOADFUNCTION

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
	SUBROUTINE MAXNORM(COEFF_SOL, MAXERR)	! MAXERR = (/ABS. NORM, REL. NORM(%)/)

	REAL*8, INTENT(IN) :: COEFF_SOL(DOF)
	REAL*8, INTENT(OUT) :: MAXERR(2)
	
	TYPE(FUNCTION_1D) EX_SOL, AP_SOL
	REAL*8 :: PHY_PT, TMP_ERR, ERR, MAXU
	INTEGER :: I, II, J, JJ, PATCH

	
! 	AP_SOL = APSOL(0.50D0, COEFF_SOL, 1)
! 	PRINT*, 'PATCH=1', AP_SOL%VAL(0)
! 	AP_SOL = APSOL(0.50D0, COEFF_SOL, 2)
! 	PRINT*, 'PATCH=2', AP_SOL%VAL(0)
	
	TMP_ERR = 0.0D0
	ERR = 0.0D0
	MAXU = 0.0D0
	
	MAXERR(:) = 0.0D0
	
! 	OPEN(11, FILE = './data/ext')
! 	OPEN(21, FILE = './data/app')
! 	OPEN(31, FILE = './data/err')
	
	DO PATCH = 1, NUMPATCH
		DO I = 1, 101
			PHY_PT = PATCHBDPT(PATCH,1) + 1.0D0*(I-1)*((PATCHBDPT(PATCH,2) - PATCHBDPT(PATCH,1))/100.0D0)
			AP_SOL = APSOL(PHY_PT, COEFF_SOL, PATCH)
			EX_SOL = EXSOL(PHY_PT)
			IF (DABS(EX_SOL%VAL(0))>MAXU) THEN
				MAXU = DABS(EX_SOL%VAL(0))
			ENDIF
			TMP_ERR = DABS(EX_SOL%VAL(0) - AP_SOL%VAL(0))
! 			WRITE(11,*) PHY_PT, EX_SOL%VAL(0)
! 			WRITE(21,*) PHY_PT, AP_SOL%VAL(0)
! 			WRITE(31,*) PHY_PT, TMP_ERR
			IF (TMP_ERR.GE.ERR) THEN
				ERR = TMP_ERR
			ENDIF
		ENDDO
	ENDDO
! 	CLOSE(11);CLOSE(21);CLOSE(31)
	
	MAXERR(1) = ERR
	MAXERR(2) = 100.0D0*ERR/MAXU
	
END SUBROUTINE MAXNORM


SUBROUTINE H_NORM_ERROR(COEFF_SOL, H_NORM)
	
	REAL*8, INTENT(OUT) :: H_NORM(2,2)	! H_NORM(1,:) = (/ABS. L2-NORM, REL. L2-NORM(%)/),  H_NORM(2,:) = (/ABS. H1-NORM, REL. H1-NORM(%)/)
	REAL*8, INTENT(IN) :: COEFF_SOL(DOF)

	TYPE(FUNCTION_1D) :: EX_SOL, AP_SOL
	REAL*8 :: H0(2), H1(2), MAX_HNORM(2,2)
	INTEGER :: I, J, K, II, JJ, KK, PATCH
	
	H0(:) = 0.0D0
	H1(:) = 0.0D0
	MAX_HNORM(:, :) = 0.0D0
	
	DO PATCH = 1, NUMPATCH
		DO K = 1, NUMGSPT(1)
			AP_SOL = APSOL(GSPT(PATCH, K), COEFF_SOL, PATCH)
			EX_SOL = EXSOL(GSPT(PATCH, K))
! 			print*, patch, k, ap_sol%val(0:1), ex_sol%val(0:1)
			H0(1) = H0(1) + (AP_SOL%VAL(0) - EX_SOL%VAL(0))**2*GSW(PATCH, K)
			H0(2) = H0(2) + EX_SOL%VAL(0)**2*GSW(1, K)
			H1(1) = H1(1) + (AP_SOL%VAL(1) - EX_SOL%VAL(1))**2*GSW(PATCH, K)
			H1(2) = H1(2) + EX_SOL%VAL(1)**2*GSW(1, K)
		ENDDO
		H_NORM(1,1) = DSQRT(DABS(H0(1)))
        H_NORM(1,2) = DSQRT(DABS(H0(1)/H0(2)))*100.0D0
        H_NORM(2,1) = DSQRT(DABS(H0(1) + H1(1)))
        H_NORM(2,2) = DSQRT(DABS(H0(1) + H1(1))/(H0(2) + H1(2)))*100.0D0
        
        DO I = 1, 2
            DO J = 1, 2
                IF (H_NORM(I, J)>=MAX_HNORM(I, J)) THEN
                    MAX_HNORM(I, J) = H_NORM(I, J)
                ENDIF
            ENDDO
        ENDDO
	ENDDO
	
END SUBROUTINE H_NORM_ERROR


END MODULE ERRORESTIMATE
