MODULE PLOT

	USE GEOMETRY
	USE GSQUAD
	USE BASIS

	IMPLICIT NONE

CONTAINS

SUBROUTINE PLOTGM()
	
	INTEGER :: PATCH, i, j, ii, jj, k, kk
	REAL*8 :: PUSUM, BSSUM, FD_P
	
	TYPE(FUNCTION_1D) :: PUTEST, BSTEST, REFVAL, P1, P2
	
	CHARACTER(LEN=2) :: CHAR_PATCH, CHAR_LOCBS
	
	OPEN(1, FILE = './data/ndx')
	DO I=1, DOF
		WRITE(1,*) NDX(:,I)
	ENDDO
	CLOSE(1)
	
! 	OPEN(1, FILE = './data/subirndx')
! 	DO I = 1, NUMPATCH
! 		DO J = 1, NUMPATCH
! 			WRITE(1,*) SUBIRNDX(I,J,:)
! 		ENDDO
! 	ENDDO
! 	CLOSE(1)

! 	OPEN(1, FILE = './data/pu_knot')
! 	WRITE(1,*) 'POLY_ORDER : ', PU_KVEC%POLY_ORDER
! 	WRITE(1,*) 'LENGTH : ', PU_KVEC%LENGTH
! 	DO I=0, PU_KVEC%LENGTH
! 		WRITE(1,102) PU_KVEC%KNOTS(I)
! 	ENDDO
! 	CLOSE(1)

! 	OPEN(1, FILE = './data/col_pt')
! 	DO I = 1, UBOUND(COL_PT,1)
! 		WRITE(1,*) COL_PT(I), 0.0D0
! 	ENDDO
! 	CLOSE(1)

! 	OPEN(1, FILE = './data/jeta')
! 	DO I = 1, UBOUND(JETA,1)
! 		WRITE(1,*) JETA(I,:), 0.0d0
! 	ENDDO
! 	CLOSE(1)
	
	OPEN(1, FILE = './data/patchbdpt')
	DO I = 1, UBOUND(PATCHBDPT,1)
		WRITE(1,*) PATCHBDPT(I,:)
	ENDDO
	CLOSE(1)
	
	OPEN(1, FILE = 'data/gspt')
	DO I = 1, NUMPATCH
		write(1,*) 'patch=',i
		DO J = 1, NUMGSPT
			WRITE(1,*) GSPT(I, J), GSW(I,J)
		ENDDO
	ENDDO
	
! 	print*, betai(2.0d0,3.0d0,5.6740d0) 

! 	DO J = 0, JORDER
! 		write(CHAR_LOCBS,fmt='(i1)') J
! 		FILENAME = trim('./data/jacobi') // CHAR_LOCBS
! 		OPEN(111, FILE=FILENAME, STATUS='UNKNOWN')
! 		DO I = 1, 101
! 			BSTEST = JACOBI_POLY(0.010D0*(I-1),J)
! 			WRITE(111,*) 0.010D0*(I-1), BSTEST%VAL(0:2)
! 		ENDDO
! 		CLOSE(111)
! 	ENDDO
	
! 	FD_P = GET_PHY_FD_JACOBI_POLY(0.50D0, 1, 1)
! 	PRINT*, dabs(FD_P - 1.59576912160573080d0)
! 	STOP
	
! 	PRINT*, DABS(DEXP(LOGGAMMA(1.0D0))-1.0D0), DABS(DEXP(LOGGAMMA(2.0D0))-1.0D0)
! 	PRINT*, DABS(DEXP(LOGGAMMA(0.50D0))-DSQRT(PI)), DABS(DEXP(LOGGAMMA(5.50D0))-(DSQRT(PI)/(2.0D0**5))*(FACTORIAL(10)/(2.0D0**(5)*FACTORIAL(5))))
! 	PRINT*, ""
! 	PRINT*, DABS(DEXP(GAMMLN(1.0D0))-1.0D0), DABS(DEXP(GAMMLN(2.0D0))-1.0D0)
! 	PRINT*, DABS(DEXP(GAMMLN(0.50D0))-DSQRT(PI)), DABS(DEXP(GAMMLN(5.50D0))-(DSQRT(PI)/(2.0D0**5))*(FACTORIAL(10)/(2.0D0**(5)*FACTORIAL(5))))
	
	
! 	DO PATCH = 1, NUMPATCH
! 		write(CHAR_PATCH,fmt='(i2)') PATCH
! 		FILENAME = trim('./data/pu') // CHAR_PATCH
! 		OPEN(111, FILE=FILENAME, STATUS='UNKNOWN')
! 		DO I = 1, 200
! 			PUTEST = PHYPU1D(PATCHBDPT(1,1) + 1.0D0*I*((PATCHBDPT(NUMPATCH,2) - PATCHBDPT(1,1))/200.0D0), PATCH)
! 			WRITE(111,*) PATCHBDPT(1,1) + 1.0D0*I*((PATCHBDPT(NUMPATCH,2) - PATCHBDPT(1,1))/200.0D0), PUTEST%VAL(0:2)
! 		ENDDO
! 		CLOSE(111)
! 	ENDDO
	
! 	DO I = 0, 1000
! 		PUSUM = 0.0D0
! 		BSSUM = 0.0D0
! 		DO PATCH = 1, NUMPATCH
! 			PUTEST = GET_BSPLINEPU1D(0.0010D0*I, PATCH)
! 			DO J = 0, IORDER
! 				BSTEST = GET_LOCBASIS(0.0010D0*I, J, PATCH)
! 				BSSUM = BSSUM + PUTEST%VAL(0)*BSTEST%VAL(0)
! 				IF (DABS(0.0010D0*I - 0.20D0)<=EPS) THEN
! 					PRINT*, PATCH, J, BSTEST
! 				ENDIF
! 			ENDDO
! 			PUSUM = PUSUM + PUTEST%VAL(0)
! 		ENDDO
! 		IF (DABS(PUSUM - 1.0D0)>EPS) THEN
! 			PRINT*, 'FAIL PU TEST', PUSUM
! 			STOP
! 		ENDIF
! 		IF (DABS(BSSUM - 1.0D0)>EPS) THEN
! 			PRINT*, 'FAIL BS TEST', BSSUM, 0.0010D0*I, PATCH
! 			STOP
! 		ENDIF
! 	ENDDO
	
! 	DO I = 0, 1000
! 		BSTEST = GET_LOCBASIS(0.010D0*(I-1), J, PATCH)
! 	ENDDO

! 	DO PATCH = 1, NUMPATCH
! 		DO I = 1,101
! 			REFVAL = PATCH_TO_REF1D(X, PATCH)
	
! 	DO PATCH = 1, NUMPATCH
! 	DO J = 0, IORDER
! 		write(CHAR_LOCBS,fmt='(i2)') J
! 		write(CHAR_PATCH, fmt='(i1)') PATCH
! 		FILENAME = trim('./data/bs') // CHAR_PATCH // CHAR_LOCBS
! 		OPEN(111, FILE=FILENAME, STATUS='UNKNOWN')
! 		DO I = 1, 101
! 			BSTEST = GET_LOCBASIS(0.010D0*(I-1), J, PATCH)
! 			WRITE(111,*) 0.010D0*(I-1), BSTEST%VAL(0:2)
! 		ENDDO
! 		CLOSE(111)
! 	ENDDO
! 	ENDDO

	102 FORMAT(1000(f20.8,1x))
END SUBROUTINE PLOTGM

END MODULE PLOT
